#!/usr/bin/env bash

summary='Switch Docker machine'
usage="Usage: dockerutil switch [OPTIONS]"

function displayUsageAndSummary {
    printf "%s\n\n%s\n" "$usage" "$summary"
}

function displayHelp {
    displayUsageAndSummary
    echo ''
    declare -A optionsTable
    local numFlags=2
    optionsTable["0,0"]='-h'
    optionsTable["0,1"]='Print usage and options'
    optionsTable["1,0"]='-s NAME'
    optionsTable["1,1"]='Switch active Docker machine to NAME'
    local i=0
    while [ $i -lt $numFlags ]; do
        printf '%4s'
        printf "%-14s%s\n" "${optionsTable["$i",0]}" "${optionsTable["$i",1]}"
        ((i = i + 1))
    done
}

function displayHelpPrompt {
    echo "See 'dockerutil switch -h' for more information"
}

function switchMachine {
    eval "$(docker-machine env "$1")"
    docker-machine ls
}

while getopts ":hs:" option; do
    case "$option" in
        h)
            displayHelp
            exit 0
            ;;
        s)
            switchMachine "$OPTARG"
            switchedMachine=true
            ;;
        \?)
            echo "invalid option: -$OPTARG" >&2
            echo ''
            displayHelpPrompt
            exit 1
            ;;
        :)
            echo "option -$OPTARG requires an argument"
            echo ''
            displayHelpPrompt
            exit 1
            ;;
    esac
done

if [ -z switchedMachine ]; then
    printf 'No Docker machine specified\n\n'
    displayHelpPrompt
fi
